import type { Metadata } from "next";
import LangWrapper from "../../context/LangWrapper";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LangWrapper>{children}</LangWrapper>
      </body>
    </html>
  );
}
